# Generated by Django 4.2.16 on 2024-12-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_colaboradores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
