# Generated by Django 4.2.16 on 2024-12-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_tarea_completado_tarea_fecha_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_limite',
        ),
        migrations.AddField(
            model_name='tarea',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
